<?php

/**
 * ChampsTableUtilisateurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChampsTableUtilisateurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChampsTableUtilisateurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChampsTableUtilisateur');
    }
}