<?php

/**
 * ChampsEcranUtilisateurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChampsEcranUtilisateurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChampsEcranUtilisateurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChampsEcranUtilisateur');
    }
}