<?php

/**
 * DescriptionMenuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DescriptionMenuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DescriptionMenuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DescriptionMenu');
    }
}