<?php

/**
 * EnchainementProgrammesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnchainementProgrammesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EnchainementProgrammesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EnchainementProgrammes');
    }
}