<?php

/**
 * GedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ged');
    }
}