<?php

/**
 * TablesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TablesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TablesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tables');
    }
}