<?php

/**
 * TableUtilisateurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TableUtilisateurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TableUtilisateurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TableUtilisateur');
    }
}