<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('enchainement_programmes', 'idNom', array(
             'fields' => 
             array(
              0 => 'nom_enchainement',
              1 => 'nom_programme',
              2 => 'numero_ordre',
             ),
             'type' => 'unique',
             ));
        $this->addIndex('ged', 'idCle', array(
             'fields' => 
             array(
              0 => 'cle_0',
              1 => 'cle_1',
              2 => 'cle_2',
              3 => 'cle_3',
              4 => 'cle_4',
              5 => 'cle_5',
              6 => 'cle_6',
              7 => 'cle_7',
              8 => 'cle_8',
              9 => 'cle_9',
             ),
             ));
        $this->addIndex('ged', 'idDate', array(
             'fields' => 
             array(
              0 => 'date_creation',
             ),
             ));
        $this->addIndex('tables', 'idNom', array(
             'fields' => 
             array(
              0 => 'id_table',
              1 => 'nom',
             ),
             'type' => 'unique',
             ));
        $this->addIndex('utilisateur', 'idLogin', array(
             'fields' => 
             array(
              0 => 'login',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('enchainement_programmes', 'idNom', array(
             'fields' => 
             array(
              0 => 'nom_enchainement',
              1 => 'nom_programme',
              2 => 'numero_ordre',
             ),
             'type' => 'unique',
             ));
        $this->removeIndex('ged', 'idCle', array(
             'fields' => 
             array(
              0 => 'cle_0',
              1 => 'cle_1',
              2 => 'cle_2',
              3 => 'cle_3',
              4 => 'cle_4',
              5 => 'cle_5',
              6 => 'cle_6',
              7 => 'cle_7',
              8 => 'cle_8',
              9 => 'cle_9',
             ),
             ));
        $this->removeIndex('ged', 'idDate', array(
             'fields' => 
             array(
              0 => 'date_creation',
             ),
             ));
        $this->removeIndex('tables', 'idNom', array(
             'fields' => 
             array(
              0 => 'id_table',
              1 => 'nom',
             ),
             'type' => 'unique',
             ));
        $this->removeIndex('utilisateur', 'idLogin', array(
             'fields' => 
             array(
              0 => 'login',
             ),
             ));
    }
}